# Generated by Django 6.0.4 on 2026-04-24 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('formula', models.TextField(help_text='Descripción textual de la fórmula')),
                ('unidad', models.CharField(help_text='Ej: número entero o porcentaje', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del Servicio')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Servicio')),
                ('piso', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicación/Piso')),
            ],
        ),
        migrations.CreateModel(
            name='ValorIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(default=2025)),
                ('mes', models.IntegerField(choices=[(0, 'Anual (Todos los meses)'), (1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('valor_calculado', models.FloatField()),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='api_hospital.indicador')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='api_hospital.servicio')),
            ],
            options={
                'verbose_name': 'Valor de Indicador',
                'verbose_name_plural': 'Valores de Indicadores',
            },
        ),
    ]
